import { PointCloudData } from "../types";

export type ExportFormat = "ply" | "xyz" | "pcd" | "csv";

export const EXPORT_FORMATS: Array<{
  id: ExportFormat;
  label: string;
  ext: string;
  blurb: string;
}> = [
  { id: "ply", label: "PLY", ext: "ply", blurb: "Universal · CloudCompare, Blender, MeshLab" },
  { id: "xyz", label: "XYZ", ext: "xyz", blurb: "Texto X Y Z R G B" },
  { id: "pcd", label: "PCD", ext: "pcd", blurb: "PCL / ROS" },
  { id: "csv", label: "CSV", ext: "csv", blurb: "x,y,z,r,g,b · Excel, pandas" },
];

const num = (n: number): string => {
  const v = +n.toFixed(6);
  return Object.is(v, -0) ? "0" : String(v);
};

const c255 = (n: number): number => {
  const v = Math.round(n * 255);
  return v < 0 ? 0 : v > 255 ? 255 : v;
};

// Reinterpret the bits of a packed RGB uint32 as a float32, as PCL expects.
const _f32 = new Float32Array(1);
const _u32 = new Uint32Array(_f32.buffer);
const packRgbToFloat = (r: number, g: number, b: number): number => {
  _u32[0] = (((r << 16) | (g << 8) | b) & 0xffffff) >>> 0;
  return _f32[0];
};

const pointCount = (data: PointCloudData): number => data.positions.length / 3;

export const toPLY = (data: PointCloudData): string => {
  const { positions, colors } = data;
  const n = pointCount(data);
  const head =
    "ply\n" +
    "format ascii 1.0\n" +
    "comment Generated by DepthGen 3D\n" +
    `element vertex ${n}\n` +
    "property float x\n" +
    "property float y\n" +
    "property float z\n" +
    "property uchar red\n" +
    "property uchar green\n" +
    "property uchar blue\n" +
    "end_header\n";

  const rows: string[] = new Array(n);
  for (let i = 0; i < n; i++) {
    const p = i * 3;
    rows[i] =
      `${num(positions[p])} ${num(positions[p + 1])} ${num(positions[p + 2])} ` +
      `${c255(colors[p])} ${c255(colors[p + 1])} ${c255(colors[p + 2])}`;
  }
  return head + rows.join("\n") + "\n";
};

export const toXYZ = (data: PointCloudData): string => {
  const { positions, colors } = data;
  const n = pointCount(data);
  const rows: string[] = new Array(n);
  for (let i = 0; i < n; i++) {
    const p = i * 3;
    rows[i] =
      `${num(positions[p])} ${num(positions[p + 1])} ${num(positions[p + 2])} ` +
      `${c255(colors[p])} ${c255(colors[p + 1])} ${c255(colors[p + 2])}`;
  }
  return rows.join("\n") + "\n";
};

export const toCSV = (data: PointCloudData): string => {
  const { positions, colors } = data;
  const n = pointCount(data);
  const rows: string[] = new Array(n + 1);
  rows[0] = "x,y,z,r,g,b";
  for (let i = 0; i < n; i++) {
    const p = i * 3;
    rows[i + 1] =
      `${num(positions[p])},${num(positions[p + 1])},${num(positions[p + 2])},` +
      `${c255(colors[p])},${c255(colors[p + 1])},${c255(colors[p + 2])}`;
  }
  return rows.join("\n") + "\n";
};

export const toPCD = (data: PointCloudData): string => {
  const { positions, colors } = data;
  const n = pointCount(data);
  const head =
    "# .PCD v0.7 - Point Cloud Data file format\n" +
    "VERSION 0.7\n" +
    "FIELDS x y z rgb\n" +
    "SIZE 4 4 4 4\n" +
    "TYPE F F F F\n" +
    "COUNT 1 1 1 1\n" +
    `WIDTH ${n}\n` +
    "HEIGHT 1\n" +
    "VIEWPOINT 0 0 0 1 0 0 0\n" +
    `POINTS ${n}\n` +
    "DATA ascii\n";

  const rows: string[] = new Array(n);
  for (let i = 0; i < n; i++) {
    const p = i * 3;
    const rgb = packRgbToFloat(c255(colors[p]), c255(colors[p + 1]), c255(colors[p + 2]));
    rows[i] = `${num(positions[p])} ${num(positions[p + 1])} ${num(positions[p + 2])} ${rgb}`;
  }
  return head + rows.join("\n") + "\n";
};

const ENCODERS: Record<ExportFormat, (d: PointCloudData) => string> = {
  ply: toPLY,
  xyz: toXYZ,
  pcd: toPCD,
  csv: toCSV,
};

export const serializePointCloud = (data: PointCloudData, format: ExportFormat): string =>
  ENCODERS[format](data);

export const downloadPointCloud = (
  data: PointCloudData,
  format: ExportFormat,
  baseName = "pointcloud"
): void => {
  const text = serializePointCloud(data, format);
  const blob = new Blob([text], { type: "text/plain;charset=utf-8" });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = `${baseName}.${format}`;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  setTimeout(() => URL.revokeObjectURL(url), 1000);
};
